INSERT INTO estilos_musicales(estilo_nombre) values ("Música clásica");
INSERT INTO estilos_musicales(estilo_nombre) values ("Jazz");
INSERT INTO estilos_musicales(estilo_nombre) values ("Blues");
INSERT INTO estilos_musicales(estilo_nombre) values ("Góspel");
INSERT INTO estilos_musicales(estilo_nombre) values ("Soul");
INSERT INTO estilos_musicales(estilo_nombre) values ("Pop");
INSERT INTO estilos_musicales(estilo_nombre) values ("Rock and Roll");
INSERT INTO estilos_musicales(estilo_nombre) values ("Country");
INSERT INTO estilos_musicales(estilo_nombre) values ("Disco");
INSERT INTO estilos_musicales(estilo_nombre) values ("Techno");
INSERT INTO estilos_musicales(estilo_nombre) values ("Reggae");
INSERT INTO estilos_musicales(estilo_nombre) values ("Salsa");
INSERT INTO estilos_musicales(estilo_nombre) values ("Flamenco");
INSERT INTO estilos_musicales(estilo_nombre) values ("Ranchera");
INSERT INTO estilos_musicales(estilo_nombre) values ("Hip hop/Rap");
INSERT INTO estilos_musicales(estilo_nombre) values ("Reggaetón");
INSERT INTO estilos_musicales(estilo_nombre) values ("Metal");
INSERT INTO estilos_musicales(estilo_nombre) values ("Funk");
INSERT INTO estilos_musicales(estilo_nombre) values ("Bossa Nova");
INSERT INTO estilos_musicales(estilo_nombre) values ("Música melódica");